name: colecoes
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

#1.0.0
#1.0.1
#1.1.0
#2.0.0
environment:
  sdk: ^3.0.6 #versionamento semântico
  #major,minor,patch

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.21.0
